###############################################################################
# @file: Makefile
#
# Simple makefile for project maintanence, usage, and testing 
#
# @creator: 8/1/22 Bujji Setty (selagamsetty@wisc.edu)
# @modified: 8/5/22 Bujji Setty (selagamsetty@wisc.edu)
#
###############################################################################


all:
	@gcc -o moap_exec driver.c -m64 

clean: 
	@rm -f *.out

# Feel free to add any additional commands that may make testing easier. Our 
# grading scripts will be using the version of this file that was provided to 
# you when the project was released. 
#         file = $${file//.c/} ; \

